services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - datasphere
#    volumes:
#      - dataspace
  postgres:
    image: 'postgres:16.2-alpine3.19'
    env_file:
      - .env
#    environment:
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
    ports:
      - '5000:5432'
    networks:
      - datasphere
#    volumes:
#      - dataspace

  redis:
    image: 'redis:7.2.4-alpine'
    ports:
      - '6000:6379'
    networks:
      - datasphere
#    volumes:
#      - dataspace

volumes:
  dataspace:

networks:
  datasphere:
    driver:
      "bridge"
