services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5000:5432'
    networks:
      - datasphere
    volumes:
      - dataspace:/db

  redis:
    image: 'redis:latest'
    ports:
      - '5001:6379'
    networks:
      - datasphere
    volumes:
      - dataspace:/cache

volumes:
  dataspace:

networks:
  datasphere:
    driver:
      "bridge"
