storageroot: "./storage/"
jwt:
  token:
    expiration-time: 1440000
server:
  port: 3000
spring:
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  main:
    web-application-type: servlet
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://personalprojectplanner-postgres-1:5432/mydatabase"
    username: "myuser"
    password: "secret"
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: false
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    root: warn
    com.project.planner: trace
